### ISSUE TITLE
安装的时候存在权限问题

### ISSUE THREAD

**Issue by brandonxiang** [youzan/zan-proxy#1]
![image](https://user-images.githubusercontent.com/12969424/39132188-d7c4c8bc-4743-11e8-8c5c-e77442fe0591.png)

创建目录mkdir存在权限问题。

**Comment by mickeyinfoshan** [comment]
[fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions)看看这个帮助到你了吗？

**Comment by Emily90** [comment]
同样问题

**Comment by localSummer** [comment]
使用npm会出现这个问题，我这用cnpm安装成功

**Comment by delai** [comment]
实测没有问题哦

**Comment by delai** [comment]
一般是本地用户目录里的.npm 目录的权限问题， chmod  chown修复下就好了。
