### ISSUE TITLE
跟anyproxy、whistle有什么不一样的地方？

### ISSUE THREAD

**Issue by yuu2lee4** [youzan/zan-proxy#11]

**Comment by mickeyinfoshan** [comment]
大部分功能都是相似的，但是有几个anyproxy, whistle不具有的特点或功能：

1. 支持在团队成员间共享的远程转发规则集；
2. 可以切换Host；
3. 自定义插件的开发学习成本更低，功能也更强大；

**Comment by yuu2lee4** [comment]
可以代替charles？

**Comment by liaoyinglong** [comment]
@yuu2lee4  老哥，可以看一下这个视频，第三部分，有具体介绍以及问答。
https://tech.youzan.com/fe-open-day-2018/

**Comment by yuu2lee4** [comment]
66666

**Comment by delai** [comment]
@yuu2lee4 有计划的，我们内部已经在用一个桌面版了，对外的话还需要时间
