### ISSUE TITLE
【漏洞】目录穿越导致任意文件读取

### ISSUE THREAD

**Issue by 0xbug** [youzan/zan-proxy#12]
看到有几个接口需要读取本地文件，代码没有判断 拼接路径的真实路径是否合法，最终导致文件读取
https://github.com/youzan/zan-proxy/blob/a0bf58f2b6255da17038de1c5e98ca10063a1a91/src/App/services/mockData.ts#L162-L164

复现方法：
http://127.0.0.1:40001/data/getdatafile?id=../../../../../../../../../etc/passwd

修复建议：
使用 `fs.realpath` 判断真实路径

**Comment by delai** [comment]
@0xbug 要不你来提个pr？

**Comment by mickeyinfoshan** [comment]
merged
