### ISSUE TITLE
导入规则集无效

### ISSUE THREAD

**Issue by Xbantian** [youzan/zan-proxy#2]
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

![image](https://user-images.githubusercontent.com/24351545/39252581-8e96c4b0-48d8-11e8-98fd-dcbb0516a029.png)

文件的type是个‘’

**Comment by mickeyinfoshan** [comment]
fixed [4.0.5](https://github.com/youzan/zan-proxy/pull/5)
