### ISSUE TITLE
【bug】Invalid Host header

### ISSUE THREAD

**Issue by ypliypli** [youzan/zan-proxy#20]
正确命中转发规则，zan-proxy-target 链接用浏览器打方案，但是代理后用虚拟域名和 127.0.0.1 都提示 Invalid Host header
![image](https://user-images.githubusercontent.com/14327002/41982116-3078b198-7a5d-11e8-9ac5-3809976a96be.png)

**Comment by mickeyinfoshan** [comment]
是不是服务器127.0.0.1:8089 检查了Host头，只能是有特定Host头才能访问?

**Comment by mickeyinfoshan** [comment]
closed
