### ISSUE TITLE
[bug]删除规则时报错 Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by yinxin630** [youzan/zan-proxy#21]
我创建了名称为 `预发+线上` 的规则集, 删除该规则集时报错: 

`Error: ENOENT: no such file or directory, unlink '/Users/xxx/.front-end-proxy/rule/root_预发 线上.json'`

查看该目录下, 存在 `root_预发+线上.json` 文件

**Comment by mickeyinfoshan** [comment]
会不会是特殊符号+的问题？
