### ISSUE TITLE
返回mock数据为空，监控台有数据

### ISSUE THREAD

**Issue by ayiaq1** [youzan/zan-proxy#23]
![1](https://user-images.githubusercontent.com/3860498/42144920-85674444-7df0-11e8-8b4e-aa86b0473e82.png)
![2](https://user-images.githubusercontent.com/3860498/42144921-86606c7c-7df0-11e8-94b8-e1f5dc279896.png)
![3](https://user-images.githubusercontent.com/3860498/42144927-8a116ba0-7df0-11e8-86c4-5ca72c9e5298.png)
![4](https://user-images.githubusercontent.com/3860498/42144932-8e49b632-7df0-11e8-895c-bb732950ece6.png)

监控台返回了我mock的数据，但是实际页面 这个请求返回数据为空，ajax error status为0

**Comment by mickeyinfoshan** [comment]
预计有跨域的问题，需要添加响应的响应头access-control-allow-origin等

**Comment by ayiaq1** [comment]
@mickeyinfoshan 返回的是mock数据，浏览器status Code为200 肯定不是跨域问题，我看监控台数据是在body里面的，这个能配置为data么

**Comment by mickeyinfoshan** [comment]
这个就是http报文体啊，proxy已经把数据返回出去了，可以直接请求看看。如果直接请求可以拿到数据，那基本可以确定是项目的设置问题或者跨域的问题了

**Comment by ayiaq1** [comment]
规则配置：增加响应头
access-control-allow-origin  ：  http://localhost

access-control-allow-credentials : true

拦截数据并且返回自定义json通过
