### ISSUE TITLE
[bug]http转发到本地时, 如果地址中带参数会报"does not exist"

### ISSUE THREAD

**Issue by yinxin630** [youzan/zan-proxy#36]
![image](https://user-images.githubusercontent.com/6939365/42357486-c3b8b986-810a-11e8-96b6-34630921879d.png)
![image](https://user-images.githubusercontent.com/6939365/42357503-d54960d8-810a-11e8-954c-1f333d55faa6.png)

**Comment by yinxin630** [comment]
补充, 带hash值是可以的

**Comment by mickeyinfoshan** [comment]
设置的转发规则会把地址中的参数带到生成的最终目标路径，如果需要过滤地址中的参数可以在匹配条件中设置对应的正则表达式，你这里的例子就是 
`bridge.damai.cn/(.*)(\?.*)?`

**Comment by yinxin630** [comment]
`bridge.damai.cn/(.*)(\?.*)?` 这个不行
`bridge.damai.cn/(.*)(?:\?.*)` 这样子可以
感觉这处很容易出错, 应该在文档里着重提醒.
另外看看可不可以在程序上规避这种情况, 比如对结果做处理(去掉params和hash)后再匹配本地文件

**Comment by mickeyinfoshan** [comment]
我先在文档上说补充说明，程序上规避会在近期上想办法
