### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by teneresa** [youzan/zan-proxy#39]
Hi, my name is Valeria. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your app. If it's something you're interested in, please, let me know!
Best,
Valeria

**Comment by mickeyinfoshan** [comment]
@teneresa 
Hey, Valeria
I‘m so pleased that we can collaborate on the project. It would be appreciated if you could design a logo for our project.
Feel free to make any pull requests.

**Comment by mickeyinfoshan** [comment]
Zan means 👍 (like) in Chinese. No special requirements at all!

**Comment by teneresa** [comment]
Ok, I'll prepare some options soon :)

**Comment by teneresa** [comment]
Hi Mickey, here is an option for the logo. This is a combination of "like" symbol and server icon. Please, let me know what do you think?
![zan_logo](https://user-images.githubusercontent.com/39339824/42605400-1e0bef06-854e-11e8-8492-290b80967cd9.jpg)

**Comment by teneresa** [comment]
Hi Mickey, here are a color option and icon variations. 
![zan logo-01](https://user-images.githubusercontent.com/39339824/42656437-abcc1800-85f5-11e8-8ef4-437b03656203.jpg)

**Comment by mickeyinfoshan** [comment]
Wow~ That's amazing! You've done a great job! I'd like to use it in the [README](https://github.com/youzan/zan-proxy/blob/master/README.md) and the [website](https://youzan.github.io/zan-proxy/)!

**Comment by teneresa** [comment]
Mickey, I'm happy to hear this, thank you! I uploaded all the required files and created a pull-request. Please merge it if everything is Ok :)
