### ISSUE TITLE
Host更改无效

### ISSUE THREAD

**Issue by whitemiaool** [youzan/zan-proxy#40]
根据文档  chrome搭配SwitchyOmega插件使用，SwitchyOmega配置如下
![image](https://user-images.githubusercontent.com/22339198/42427385-d77e6f08-8360-11e8-8ef2-ab99c70c9b90.png)
切换到配置文件
![image](https://user-images.githubusercontent.com/22339198/42427444-1980106e-8361-11e8-848d-32d8935cfe95.png)

youzan配置如下
![image](https://user-images.githubusercontent.com/22339198/42427467-2d173134-8361-11e8-8ade-b3b705932698.png)
host文件如下
![image](https://user-images.githubusercontent.com/22339198/42427485-3d627940-8361-11e8-9f13-f1c725f9db03.png)

打开baidu如下
![image](https://user-images.githubusercontent.com/22339198/42427510-6c50c5c2-8361-11e8-830f-f613580a6a1b.png)

youzan console as follow
![image](https://user-images.githubusercontent.com/22339198/42427556-adf7b418-8361-11e8-803d-a79b8849999a.png)

WTF？？？someone help me???

**Comment by mickeyinfoshan** [comment]
@whitemiaool 更新后已修复

**Comment by whitemiaool** [comment]
@mickeyinfoshan 这就是我刚更新完测试的。。。。。

**Comment by mickeyinfoshan** [comment]
@whitemiaool 出现这种情况还可能是证书没有信任，关于证书部分可以参考这里：https://youzan.github.io/zan-proxy/book/quick-start/cert.html

**Comment by whitemiaool** [comment]
@mickeyinfoshan windows系统呢？
