### ISSUE TITLE
mock下大数据保存失败

### ISSUE THREAD

**Issue by ayiaq1** [youzan/zan-proxy#49]
mock下json数据如果children超过1000条保存失败，是否有写入文件大小限制？ 
如果有我是否可以通过替换本地mock的缓存文件来达到mock效果？本地mock缓存存放到什么地方的呢

**Comment by mickeyinfoshan** [comment]
可以通过把接口转发到本地文件达到mock效果，转发目标写成mock文件的路径即可。
超过1000条的不能保存的问题会在近期跟进。
@ayiaq1

**Comment by mickeyinfoshan** [comment]
fixed
