### ISSUE TITLE
编辑规则时, 请求动作新增和删除功能不合理

### ISSUE THREAD

**Issue by yinxin630** [youzan/zan-proxy#60]
![https://cdn.suisuijiang.com/ImageMessage/5adad39555703565e7903f78_1533541297924.png?width=1878&height=682](https://cdn.suisuijiang.com/ImageMessage/5adad39555703565e7903f78_1533541297924.png?width=1878&height=682)

如图, 新增是添加到下面的, 删除却是从上面开始
我新增一个规则然后不想要了, 操作起来就很尴尬

**Comment by mickeyinfoshan** [comment]
closed
