### ISSUE TITLE
windows下设置HOME环境变量后, postinstall和zan-proxy的HOME目录不一致.

### ISSUE THREAD

**Issue by cntsw** [youzan/zan-proxy#66]
# 环境
系统: windows7 x64
node: v8.9.4
系统的HOME环境变量被设置到了其他的盘

# 问题
[src/bin/index.ts#L8](https://github.com/youzan/zan-proxy/blob/809aa23f515fa0a29eca1db5b96d7ece3ca2312a/src/bin/index.ts#L8)
引入`selfupdate`的时候, 会导致`process.env.HOME`变量改变, 所以执行`resetDataFile.js`文件和启动zan-proxy的时候HOME是不同的.
```javascript
console.log(process.env.HOME);    // E:\home
const npm = require('selfupdate');
console.log(process.env.HOME);   // C:\Users\xxx
```

是否可以考虑改为用`os.homedir()`来获取HOME, 这样的话程序更健 ?
参考: https://stackoverflow.com/a/9081436

**Comment by mickeyinfoshan** [comment]
merged

**Comment by mickeyinfoshan** [comment]
升级到4.0.22版本 感谢 @cntsw
