### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by liushenyun** [youzan/zan-proxy#77]
请问，运行的时候报这个错误怎么解决？
openssl已经安装了，但是openssl --version 不行
![image](https://user-images.githubusercontent.com/21031604/47349494-57e13800-d6e6-11e8-8644-84fdb040f845.png)

**Comment by jituanlin** [comment]
`openssl --version`命令报的错是没有找到命令吗
试试把OpenSSL的路径添加到环境变量里
