### ISSUE TITLE
zan-proxy启动后 zan-proxy 打包的网址（:40001）报错 localhost:8001挂起不响应

### ISSUE THREAD

**Issue by guojingwen** [youzan/zan-proxy#8]
guojingwen ~$zan-proxy
当前已是最新版本
开始同步远程规则集
同步远程规则集结束
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md .nvm/versions/node/v8.10.0/lib/node_modules/zan-proxy/dist/App/manager/index.js:50:18
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md .nvm/versions/node/v8.10.0/lib/node_modules/zan-proxy/dist/App/plugin-manager/index.js:124:13
Proxy Port: 8001
Manager: http://192.168.221.95:40001

guojingwen ~$nvm list
         v6.9.2
         v7.2.0
         v8.3.0
->      v8.10.0
         system
default -> v8.10.0
node -> stable (-> v8.10.0) (default)
stable -> 8.10 (-> v8.10.0) (default)
iojs -> N/A (default)
guojingwen ~$node -v
v8.10.0
guojingwen ~$npm -v
5.6.0
guojingwen ~$zan-proxy -V
4.0.9

**Comment by guojingwen** [comment]
安装4.0.3  就OK,  这是个 bug!

**Comment by guojingwen** [comment]
坑了我好几个小时

**Comment by mickeyinfoshan** [comment]
请问是怎么操作的？这边没办法复现

**Comment by delai** [comment]
先关掉了
