### ISSUE TITLE
zan-proxy 启动失败了，麻烦帮忙看看什么问题

### ISSUE THREAD

**Issue by qianzhaoy** [youzan/zan-proxy#9]
以下是错误信息和有关版本号，麻烦帮看看应该如何解决

![image](https://user-images.githubusercontent.com/14267409/39954124-7643ef66-55ec-11e8-9e13-aff53132e761.png)

**Comment by mickeyinfoshan** [comment]
这是个bug，应用尝试删除目录`~/.front-end-proxy/traffic`失败了，可以手动删除后重启

**Comment by mickeyinfoshan** [comment]
fixed
