### ISSUE TITLE
请问是否支持windows操作系统？

### ISSUE THREAD

**Issue by guotao** [youzan/zan-proxy#98]
如题，win7安装完成，运行报错：

> (node:5468) UnhandledPromiseRejectionWarning: Unable to load config info from /u
sr/local/ssl/openssl.cnf

Mac下用起来很方便，谢谢作者的分享。

**Comment by kainstar** [comment]
目前暂不支持，后期会考虑一定程度上对 window 做适配

**Comment by AmmyXu** [comment]
请问现在支持windows了吗
